[package]
name = "mongodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "../../" }
tokio = "1.15.0"
dotenv = "0.15.0"
twilight-model = "0"