name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gateway:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      working-directory: gateway
      run: cargo check
    - name: Tests
      working-directory: gateway
      run: cargo test
  
  interactions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      working-directory: interactions
      run: cargo check
    - name: Tests
      working-directory: interactions
      run: cargo test
