name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update toolchain
      run: rustup update stable
    - name: Check
      run: cargo check --features all
    - name: Tests
      run: cargo test --features all