name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gateway:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      working-directory: ./gateway
      run: cargo check --verbose
    - name: Tests
      working-directory: ./gateway
      run: cargo test --verbose
  
  interactions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      working-directory: ./interaction
      run: cargo check --verbose
    - name: Tests
      working-directory: ./interaction
      run: cargo test --verbose
