name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gateway:

    runs-on: ubuntu-latest

    steps:
    - run: cd gateway
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
  
  interactions:

    runs-on: ubuntu-latest

    steps:
    - run: cd interactions
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
